### ISSUE TITLE
Trying to run exabayes with htcondor, is it possible?

### ISSUE THREAD

**Issue by asgarciap** [aberer/exabayes#6]
Hi,
I'm trying to run exabayes within htcondor. Is it possible? I'm having some issues and I can't make it work. Can anyone hereh help me with that?
Will bring more details if so.
Regards.

**Comment by aberer** [comment]
Hello there,

please feel free to post the details, but I do not have particular
knowledge about htcondor, so I do not know if I really will be able to
help.

-Andre


Mr. Lucius Fox writes:
